---
language: node_js
node_js:
  - "6"

sudo: required

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

git:
  depth: 10

services:
  - mongodb

before_install:
  - git --version
  - mongod --version
  - npm install -g adapt-cli
  - adapt --version

install:
  - npm config set spin false
  - npm install

matrix:
  fast_finish: true